apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-service
  name: my-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: my-service
      port: 80
      protocol: TCP
  selector:
    app: my-deploy
